from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
import datetime

@dataclass
class Report:
    uuid: str
    status: str
    verdict: str
    score: int
    family: Optional[str] = None
    md5: Optional[str] = None
    tags: List[str] = field(default_factory=list)
    behavior: Dict[str, Any] = field(default_factory=dict)
    yara_rules: List[str] = field(default_factory=list)
    apt_group: Optional[str] = None
    campaign: Dict[str, str] = field(default_factory=dict)
    imphash: Optional[str] = None
    attribution_confidence: int = 0

    @property
    def genetic_analysis_summary(self) -> str:
        """Explains the attribution logic in English."""
        if self.attribution_confidence > 80:
            return f"Code DNA (ImpHash) and TTP behaviors match known {self.apt_group} profiles with {self.attribution_confidence}% confidence."
        elif self.attribution_confidence > 50:
            return f"Suspicious API calls align with {self.apt_group} profile, but genetic match is inconclusive."
        return "Insufficient genetic data. ZeroScout operated in pure heuristic mode."

    def generate_yara_rule(self) -> str:
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        rule_name = f"ZeroScout_Auto_{self.md5[:6]}_{self.score}"
        
        strings = '\t\t$magic = { 4D 5A }\n'
        if self.imphash and self.imphash != "N/A":
            strings += f'\t\t$imphash = "{self.imphash}"\n'
        
        intel = self.behavior.get("intelligence", {})
        for i, wallet in enumerate(intel.get("wallets", [])):
            strings += f'\t\t$wallet_{i} = "{wallet}" ascii\n'

        return f"""/*
   GENERATED BY ZEROSCOUT AUTONOMOUS DEFENSE
   Hunter: Umid Mammadov
   Target Family: {self.family}
*/
rule {rule_name} {{
    meta:
        description = "Auto-generated rule by ZeroScout Engine"
        author = "Umid Mammadov (ZeroScout)"
        date = "{date_str}"
        severity = "CRITICAL"
        apt_actor = "{self.apt_group}"
    strings:
{strings}
    condition:
        $magic and (any of ($wallet*) or defined($imphash))
}}"""

    def generate_sigma_rule(self) -> str:
        ips = [n['ip'] for n in self.behavior.get('network', [])]
        ip_block = '\n            - '.join([f"'{ip}'" for ip in ips]) if ips else "'0.0.0.0'"
        return f"""title: Detect {self.apt_group} Activity via ZeroScout
id: zs-auto-{self.uuid[:8]}
status: experimental
description: Auto-generated SIGMA rule by ZeroScout for C2 communication
author: ZeroScout Automation
logsource:
    category: firewall
detection:
    selection:
        DestinationIp:
            - {ip_block}
    condition: selection
level: critical"""